name = "JointCMBLikelihoods"
uuid = "2c8e3d89-f67c-471a-809d-d090cd2f3b6c"
version = "0.1.0"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CMBForegrounds = "fc0df5e6-91e0-40ab-a79d-ad91d7e99724"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"

[sources]
CMBForegrounds = {url = "https://github.com/JuliaCosmologicalLikelihoods/CMBForegrounds.jl", rev = "v0.4.1"}

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
JointCMBLikelihoodsChainRulesCoreExt = "ChainRulesCore"
JointCMBLikelihoodsMooncakeExt = "Mooncake"

[compat]
Artifacts = "1"
CMBForegrounds = "0.4"
ChainRulesCore = "1"
JSON = "0.21"
LinearAlgebra = "1"
Mooncake = "0.5"
NPZ = "0.4.3"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ADTypes", "ChainRulesCore", "DifferentiationInterface", "ForwardDiff", "Mooncake"]
